from collections.abc import Callable

ALIGN_CENTER_VERTICAL: int
ALL: int
BORDER_NONE: int
BOTTOM: int
EVT_BUTTON: object
EVT_SPINCTRL: object
EVT_TEXT: object
EXPAND: int
FONTFAMILY_TELETYPE: int
ICON_ERROR: int
LEFT: int
OK: int
RIGHT: int
TE_MULTILINE: int
TE_READONLY: int
VERTICAL: int

class PyDeadObjectError(RuntimeError): ...

class FontInfo:
    def __init__(self, point_size: int) -> None: ...
    def Family(self, family: int) -> FontInfo: ...
    def FaceName(self, face_name: str) -> FontInfo: ...

class Font:
    def __init__(self, font_info: FontInfo) -> None: ...
    def IsOk(self) -> bool: ...

class FontEnumerator:
    @staticmethod
    def IsValidFacename(face_name: str) -> bool: ...

class Colour:
    def __init__(self, colour: str) -> None: ...

class CommandEvent: ...

class Size:
    width: int
    height: int

class Window:
    def Bind(self, event: object, handler: Callable[[CommandEvent], None]) -> None: ...
    def SetBackgroundColour(self, colour: Colour) -> None: ...
    def GetBackgroundColour(self) -> Colour: ...
    def GetClientSize(self) -> Size: ...

class Frame(Window):
    def __init__(
        self, parent: Window | None, title: str, size: tuple[int, int]
    ) -> None: ...
    def Centre(self) -> None: ...
    def IsBeingDeleted(self) -> bool: ...
    def Show(self, show: bool) -> None: ...

class Panel(Window):
    def __init__(self, parent: Window) -> None: ...
    def SetSizer(self, sizer: BoxSizer) -> None: ...

class BoxSizer:
    def __init__(self, orient: int) -> None: ...
    def Add(
        self, item: object, proportion: int, flag: int = 0, border: int = 0
    ) -> None: ...

class FlexGridSizer(BoxSizer):
    def __init__(self, rows: int, cols: int, vgap: int, hgap: int) -> None: ...
    def AddGrowableCol(self, idx: int, proportion: int) -> None: ...

class SpinCtrl(Window):
    def __init__(self, parent: Window, min: int, max: int, initial: int) -> None: ...
    def GetValue(self) -> int: ...

class CheckBox(Window):
    def __init__(self, parent: Window, label: str) -> None: ...
    def SetValue(self, value: bool) -> None: ...
    def GetValue(self) -> bool: ...

class TextCtrl(Window):
    def __init__(
        self, parent: Window, style: int = 0, size: tuple[int, int] = ...
    ) -> None: ...
    def Clear(self) -> None: ...
    def GetValue(self) -> str: ...
    def SetValue(self, value: str) -> None: ...

class Button(Window):
    def __init__(self, parent: Window, label: str) -> None: ...
    def Disable(self) -> None: ...
    def Enable(self) -> None: ...

class StaticText(Window):
    def __init__(self, parent: Window, label: str) -> None: ...

class App:
    def __init__(self, redirect: bool) -> None: ...
    def MainLoop(self) -> None: ...

def CallAfter(
    callable_obj: Callable[..., object], *args: object, **kwargs: object
) -> None: ...
def MessageBox(message: str, caption: str, style: int) -> int: ...
