from wx import Colour, Font, Window

STC_EDGE_NONE: int
STC_STYLE_DEFAULT: int
STC_STYLE_LINENUMBER: int
STC_WRAP_NONE: int

class StyledTextCtrl(Window):
    def __init__(self, parent: Window, style: int = 0) -> None: ...
    def ClearAll(self) -> None: ...
    def GetFirstVisibleLine(self) -> int: ...
    def GetMargins(self) -> int: ...
    def GetTextExtent(self, text: str) -> tuple[int, int]: ...
    def GetXOffset(self) -> int: ...
    def SetBackgroundColour(self, colour: Colour) -> None: ...
    def SetCaretLineVisible(self, visible: bool) -> None: ...
    def SetCaretWidth(self, width: int) -> None: ...
    def SetEdgeMode(self, mode: int) -> None: ...
    def SetFirstVisibleLine(self, line: int) -> None: ...
    def SetFoldMarginColour(self, use_setting: bool, colour: Colour) -> None: ...
    def SetFoldMarginHiColour(self, use_setting: bool, colour: Colour) -> None: ...
    def SetFont(self, font: Font) -> None: ...
    def SetIndentationGuides(self, show: bool) -> None: ...
    def SetMarginSensitive(self, margin: int, sensitive: bool) -> None: ...
    def SetMarginsBackground(self, colour: Colour) -> None: ...
    def SetMarginWidth(self, margin: int, pixel_width: int) -> None: ...
    def SetReadOnly(self, read_only: bool) -> None: ...
    def SetScrollWidth(self, pixel_width: int) -> None: ...
    def SetScrollWidthTracking(self, tracking: bool) -> None: ...
    def SetStyling(self, length: int, style: int) -> None: ...
    def SetText(self, text: str) -> None: ...
    def SetUndoCollection(self, collect_undo: bool) -> None: ...
    def SetUseHorizontalScrollBar(self, show: bool) -> None: ...
    def SetUseVerticalScrollBar(self, show: bool) -> None: ...
    def SetViewEOL(self, visible: bool) -> None: ...
    def SetViewWhiteSpace(self, visible: bool) -> None: ...
    def SetWrapMode(self, mode: int) -> None: ...
    def SetXOffset(self, offset: int) -> None: ...
    def SetZoom(self, zoom: int) -> None: ...
    def StartStyling(self, position: int) -> None: ...
    def StyleClearAll(self) -> None: ...
    def StyleSetBackground(self, style: int, colour: Colour) -> None: ...
    def StyleSetFont(self, style: int, font: Font) -> None: ...
    def StyleSetForeground(self, style: int, colour: Colour) -> None: ...
    def StyleSetSize(self, style: int, size_points: int) -> None: ...
